"""Literal public validator and error tokens."""
KEYWORD = "UsdAecoComplianceValidators"
REQUIREMENT_UNMEASURABLE = "RequirementUnmeasurable"
REQUIREMENT_UNMEASURABLE_CHECKER = "usdAecoComplianceValidators:RequirementUnmeasurableChecker"
SPECIFICATION_WITHOUT_APPLICABILITY = "SpecificationWithoutApplicability"
SPECIFICATION_WITHOUT_APPLICABILITY_CHECKER = "usdAecoComplianceValidators:SpecificationWithoutApplicabilityChecker"
COMPLIANCE_STALE = "ComplianceStale"
COMPLIANCE_STALE_CHECKER = "usdAecoComplianceValidators:ComplianceStaleChecker"
MISSING_DEVICE = "MissingDevice"
MISSING_DEVICE_CHECKER = "usdAecoComplianceValidators:MissingDeviceChecker"
MISPLACED_DEVICE = "MisplacedDevice"
MISPLACED_DEVICE_CHECKER = "usdAecoComplianceValidators:MisplacedDeviceChecker"
UNAPPROVED_PRODUCT = "UnapprovedProduct"
UNAPPROVED_PRODUCT_CHECKER = "usdAecoComplianceValidators:UnapprovedProductChecker"
MISSING_BINDING = "MissingBinding"
MISSING_BINDING_CHECKER = "usdAecoComplianceValidators:MissingBindingChecker"
ERROR_NAMES = ['RequirementUnmeasurable', 'SpecificationWithoutApplicability', 'ComplianceStale', 'MissingDevice', 'MisplacedDevice', 'UnapprovedProduct', 'MissingBinding']
